### ISSUE TITLE
Publish STAC meta data to production

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-data#101]

**Comment by smohiudd** [comment]
Are we using the correct extension versions in build stac?

Proj extension and raster ext versions: https://github.com/NASA-IMPACT/veda-data-airflow/blob/a47015ba2b327eb5d1f54958246cb6fb5b79ccb1/docker_tasks/build_stac/utils/stac.py#L12

cc: @anayeaye, @slesaad

**Comment by smohiudd** [comment]
Check if rio stac version is correct: https://github.com/NASA-IMPACT/veda-data-airflow/blob/a47015ba2b327eb5d1f54958246cb6fb5b79ccb1/docker_tasks/build_stac/requirements.txt#L7

Currently using 0.7.0 in airflow build stac

**Comment by anayeaye** [comment]
I confirmed that we want to use [rio-stac>=0.8.0](https://github.com/developmentseed/rio-stac/blob/main/CHANGES.md) to get the correct version of the proj extension.

I think we will also have a minor refactor to import the actual versions of the extensions used by rio-stac in airflows [build_stac/utils/stac.py](https://github.com/NASA-IMPACT/veda-data-airflow/blob/fix/various-airflow-workflow-fixes/docker_tasks/build_stac/utils/stac.py) as shown in the [rio-stac documentation for building multi-asset items](https://developmentseed.org/rio-stac/examples/Multi_assets_item/). Currently the utils method manually declares the projection version--given that, there may be other slight modifications to how the stac item is created.

**Comment by botanical** [comment]
### Summary of huddle on April 29, 2024

We're currently blocked on this being implemented https://jaas.gsfc.nasa.gov/servicedesk/customer/portal/2/GSD-3143 (creation of a NAT gateway).

Proof that there's a networking issue:
<img width="717" alt="Screenshot of ingest API showing empty list of items" src="https://github.com/NASA-IMPACT/veda-data/assets/12633533/d427c850-dfe8-40c2-b104-df9a2fcf5a37">
<img width="708" alt="Screenshot of ingest API showing Service Unavailable Error" src="https://github.com/NASA-IMPACT/veda-data/assets/12633533/7ae37389-c66c-48b3-969e-e2df119b7b3c">

We also tested the worfklow setting `STAC_INGESTOR_API_URL` to both `https://77451h4b35.execute-api.us-west-2.amazonaws.com/` and `https://dev.openveda.cloud/api/ingest/` and proved that the `veda_ingest_raster` DAG runs successfully with either values
![image](https://github.com/NASA-IMPACT/veda-data/assets/12633533/7f3f1b0f-f4ee-442f-9064-82ecc4b344d6)

TODO
- [ ] eventually add lifecycle policy to veda-pipeline-STAGE-mwaa-… buckets

cc @smohiudd @anayeaye @amarouane-ABDELHAK @ranchodeluxe

**Comment by botanical** [comment]
An additional [service desk ticket](https://jaas.gsfc.nasa.gov/servicedesk/customer/portal/2/GSD-3284) was created on May 3rd, 2024 to update the network ACL rules to allow traffic for ephemeral port range and the ticket is currently in `Security Review` status.

**Comment by botanical** [comment]
Ephemeral port range testing

-` /ingestions` with https://staging-stac.delta-backend.com/collections/hls-swir-falsecolor-composite/items/Lahaina_HLS_2023-08-13_SWIR_falsecolor_cog succeeded
- get`/ingestions/{ingestion_id}` with above ID succeeded
- https://4hrks0hk0b.execute-api.us-west-2.amazonaws.com/docs
  - `/dataset/publish` with [hls-swir-falsecolor-composite.json](https://github.com/NASA-IMPACT/veda-data/blob/main/ingestion-data/dataset-config/hls-swir-falsecolor-composite.json) which was [successful](https://b38b778f-d99b-4a00-a7b9-d4a5bff4383c.c23.us-west-2.airflow.amazonaws.com/dags/veda_ingest_raster/graph?run_id=d942a0a7-c165-4a4a-aabf-36dce63d634a_d129fb7e-8552-4cd5-b992-5b8b4772b46e_0&execution_date=2024-05-13+18%3A32%3A15.964269%2B00%3A00)
  -  `/dataset/publish` with [landsat-nighttime-thermal.json](https://github.com/NASA-IMPACT/veda-data/blob/main/ingestion-data/dataset-config/landsat-nighttime-thermal.json) which was [successful](https://b38b778f-d99b-4a00-a7b9-d4a5bff4383c.c23.us-west-2.airflow.amazonaws.com/dags/veda_ingest_raster/graph?run_id=98a698c7-38a3-4be3-b9df-52b743270690_fad67802-c7ad-4476-8ed3-e76e1e1c01f5_0&execution_date=2024-05-13+18%3A37%3A23.499529%2B00%3A00)
  - `/discover-executions/{workflow_execution_id}` with
    - `98a698c7-38a3-4be3-b9df-52b743270690` succeeded
    - `eb95f396-e5ef-4ac2-93f1-88b92b588521` succeeded

**Comment by anayeaye** [comment]
Now that we are unblocked, here are the notes from a backfill planning session with @botanical @smohiudd @ividito 

## The big backfill plan
We plan to use https://staging-stac.delta-backend.com/collections as our source of truth for the collections to publish to the VEDA instances running in MCP (we’ll do some test runs in mcp-test before moving to production).

### Promote to production working definition
Our target is to promote all the data that are currently staged the UAH hosted staging instance of VEDA to the MCP hosted test and production stacks. At a hight level:
1. Copy all staging assets from veda-data-store-staging to veda-data-store using transfer DAG
2. Publish STAC collections stored in git:veda-data/ingestion_data/collections to MCP hosted test and production catalogs using the <veda-backend>/ingest-api/collections endpoint
3. Trigger discovery-items workflow in the <workflows-api>/discovery/ endpoint using the inputs from git:veda-data/ingestion_data/<stage>/discovery-items

### Detailed plan
1. Identify the exceptions: a list of collection ids to skip (these are external and/or weird data like the LPDAAC hosted data, externally hosted vector collections, and collections with provider generated metadata like the HLS environmental justice events collections). This list of ids will be filtered out of the following automated promotion steps.
2. Wipe out mcp-test collections that aren’t in the skip list (currently mcp-test is an older snapshot of the staging STAC catalog and the assets in this catalog are in the staging S3 bucket). 
3. Copy and update git:veda-data/ingestion_data/discovery-items to new ingestion_data/production/discovery-items folder (i.e. correct buckets veda-data-store-staging-->veda-data-store and bucket prefixes should all be collection id)
4. Try this in mcp-test before scripting for production: Iterate over the staging-stac inventory csv: for each get git:veda-data/ingestion_data/collection 
  - Skip if in exception list
  - Find the correct git:veda-data/ingestion_data/collection for the collection id in the inventory csv and publish that collection via veda-backend/ingest-api/collections (if not already published by earlier backfill efforts)
  - Find the correct git:veda-data/ingestion_data/production/discovery-items input json and use as the POST body to the workflows-api/discovery endpoint to run workflows/discover-items

### Git:veda-data necessary changes
We will need to start thinking about a new release for upcoming changes to the ingestion DAGs. We discussed whether we should manage this in a new branch? Should we move the discovery items into the veda-data-airflow project? For now we have decided to proceed with a slight change to the git:veda-data folder structure to accommodate different folders for each stage. As in: we currently have discovery-items configuration for staging data which will move to /staging and a new production/ folder will be created for inputs configured from production data.

#### Restructure folders
```
ingestion_data/
	Collections (automated validation on pr)
	/staging
		/discovery-items
		/dataset-config
	/production
		/discovery-items
		/dataset-config (probably not? Probably we just automate the collection+discovery items)
```

#### Update buckets and prefixes in discovery-items 
Copy veda-data/staging/discovery-items to veda-data/production/discovery-items and
1. Update to production veda-data-store bucket
2. Update prefix to match the collection id (for many staged collections the prefix is somewhat arbitrary)

## Actions:
Backfill track
- [ ] Csv to the ticket (and steps reproduce) (@anayeaye )
- [ ] Google sheet from csv (may be in an existing sheet) (@anayeaye)
- [ ] Identify and document the exceptions list (all/done/??)
- [ ] Delete non-exceptions from mcp-test in prep for prod data (?)
- [ ] New branch of veda-data with new folder structure and updated discovery-items (@botanical )
  - New folder structure
  - Fix prefixes (random folders→exact collection id)
  - Fix bucket (veda-data-store-staging→veda-data-store)
- Run all of it in mcp-test (everyone, TBD)
- Run all of it in mcp-prod

observability & monitoring in MCP track
- [ ] Deploy veda-monitoring to MCP (@ividito @smohiudd will start to add that step to veda-deploy)

**Comment by anayeaye** [comment]
I started a new sheet to this [working backfill google spreadsheet](https://docs.google.com/spreadsheets/d/1ygIOPrFJ6mgslfVrIFP6ln_-xn2CCELmXBof4aA6BR4/edit#gid=1279663666) and loaded an inventory [staging-collections.csv](https://github.com/NASA-IMPACT/veda-data/files/15312698/staging-collections.csv) from the staging stac catalog that I generated in a notebook 
with this hacky loop:

```
from pystac_client import Client
import pandas as pd

def get_sample_files(collection):
    """return the hrefs of a cog assets if any items exist with cog assets"""
    cog_assets=[]
    try:
        item = next(collection.get_items(), None)
        if item:
            for k in item.assets.keys():
                if k != "rendered_preview":
                    asset = item.assets[k]
                    cog_assets.append({"key": k, "href": asset.get_absolute_href()})
        return cog_assets
    except:
        return cog_assets

STAC_API_URL = "https://staging-stac.delta-backend.com/"
catalog = Client.open(STAC_API_URL)

summaries = []
collections = list(catalog.get_collections())
for collection in sorted(collections, key=lambda x: x.id):
    summaries.append({
        "id": collection.id,
        "title": collection.title,
        "sample_files": get_sample_files(collection)
    })
df = pd.DataFrame(summaries)
df.to_csv("staging-collections.csv")
df
```

**Comment by botanical** [comment]
https://github.com/NASA-IMPACT/veda-data/pull/121 PR to add new directory structure and update prefixes for production

**Comment by botanical** [comment]
Potential collections to exclude are:
- 'hls-l30-002-ej-reprocessed'
- 'hls-s30-002-ej-reprocessed'
- 'ls8-covid-19-example-data'
- 'landsat-c2l2-sr-antarctic-glaciers-pine-island'
- 'landsat-c2l2-sr-lakes-aral-sea'
- 'landsat-c2l2-sr-lakes-tonle-sap'
- 'landsat-c2l2-sr-lakes-lake-balaton'
- 'landsat-c2l2-sr-lakes-vanern'
- 'landsat-c2l2-sr-antarctic-glaciers-thwaites'
- 'landsat-c2l2-sr-lakes-lake-biwa'
- 'combined_CMIP6_daily_GISS-E2-1-G_tas_kerchunk_DEMO'

**Comment by smohiudd** [comment]
The following discoveries failed in mcp-test:
ndvi_diff_Ian_2022-09-30_2022-09-05
entropy_difference_2022-09-05_2022-09-30
hls-l30-002-ej-reprocessed
ls8-covid-19-example-data
modis-lst-night-diff-2015-2022
landsat-c2l2-sr-antarctic-glaciers-pine-island
landsat-c2l2-sr-lakes-aral-sea
houston-lst-diff
nceo_africa_2017
landsat-c2l2-sr-lakes-tonle-sap
landsat-c2l2-sr-lakes-lake-balaton
EPA-annual-emissions_6B_Wastewater_Treatment_Domestic
EPA-annual-emissions_6B_Wastewater_Treatment_Industrial
EPA-annual-emissions_6D_Composting
hls-s30-002-ej-reprocessed
landsat-c2l2-sr-lakes-vanern
landsat-c2l2-sr-antarctic-glaciers-thwaites
landsat-c2l2-sr-lakes-lake-biwa
combined_CMIP6_daily_GISS-E2-1-G_tas_kerchunk_DEMO

**Comment by botanical** [comment]
- Internal server error for `modis-lst-night-diff-2015-2022` was due to incorrect bucket name. Fixed here:
https://github.com/NASA-IMPACT/veda-data/pull/125

**Comment by botanical** [comment]
For posterity, the `nceo_africa_2017` ingestion item:

```json
{
    "id": "AGB_map_2017v0m_COG",
    "bbox": [
        -18.273529509559307,
        -35.054059016911935,
        51.86423292864056,
        37.73103856358817
    ],
    "type": "Feature",
    "links": [],
    "assets": {
        "cog_default": {
            "href": "s3://nasa-maap-data-store/file-staging/nasa-map/nceo-africa-2017/AGB_map_2017v0m_COG.tif",
            "type": "image/tiff; application=geotiff; profile=cloud-optimized",
            "roles": [
                "data",
                "layer"
            ],
            "title": "Default COG Layer",
            "description": "Cloud optimized default layer to display on map",
            "raster:bands": [
                {
                    "scale": 1,
                    "nodata": "inf",
                    "offset": 0,
                    "sampling": "area",
                    "data_type": "uint16",
                    "histogram": {
                        "max": 429,
                        "min": 0,
                        "count": 11,
                        "buckets": [
                            405348,
                            44948,
                            18365,
                            6377,
                            3675,
                            3388,
                            3785,
                            9453,
                            13108,
                            1186
                        ]
                    },
                    "statistics": {
                        "mean": 37.58407913145342,
                        "stddev": 81.36678677343947,
                        "maximum": 429,
                        "minimum": 0,
                        "valid_percent": 50.42436439336373
                    }
                }
            ]
        }
    },
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    -18.273529509559307,
                    -35.054059016911935
                ],
                [
                    51.86423292864056,
                    -35.054059016911935
                ],
                [
                    51.86423292864056,
                    37.73103856358817
                ],
                [
                    -18.273529509559307,
                    37.73103856358817
                ],
                [
                    -18.273529509559307,
                    -35.054059016911935
                ]
            ]
        ]
    },
    "collection": "nceo_africa_2017",
    "properties": {
        "proj:bbox": [
            -18.273529509559307,
            -35.054059016911935,
            51.86423292864056,
            37.73103856358817
        ],
        "proj:epsg": 4326,
        "proj:shape": [
            81024,
            78077
        ],
        "end_datetime": "2017-12-31T23:59:59+00:00",
        "proj:geometry": {
            "type": "Polygon",
            "coordinates": [
                [
                    [
                        -18.273529509559307,
                        -35.054059016911935
                    ],
                    [
                        51.86423292864056,
                        -35.054059016911935
                    ],
                    [
                        51.86423292864056,
                        37.73103856358817
                    ],
                    [
                        -18.273529509559307,
                        37.73103856358817
                    ],
                    [
                        -18.273529509559307,
                        -35.054059016911935
                    ]
                ]
            ]
        },
        "proj:transform": [
            0.0008983152841195214,
            0,
            -18.273529509559307,
            0,
            -0.0008983152841195214,
            37.73103856358817,
            0,
            0,
            1
        ],
        "start_datetime": "2017-01-01T00:00:00+00:00",
        "datetime": null
    },
    "stac_version": "1.0.0",
    "stac_extensions": [
        "https://stac-extensions.github.io/projection/v1.0.0/schema.json",
        "https://stac-extensions.github.io/raster/v1.1.0/schema.json"
    ]
}
```

**Comment by anayeaye** [comment]
Here's a small first draft of an audit of the collections in veda-config datasets and the `mcp-test` stack. The unmatched collection ids are known special cases. Some of the empty collections are also expected but others may mean we need to tweak the discovery items configuration.

> **Note** I will update this comment with the results to account for the known special cases like externally hosted assets

```
import requests
STAC_API_URL = "https://test.openveda.cloud/api/stac"

missing_collections = []
empty_collections = []
dashboard_collections = ['CMIP245-winter-median-pr', 'CMIP245-winter-median-ta', 'CMIP585-winter-median-pr', 'CMIP585-winter-median-ta', 'EPA-annual-emissions_1A_Combustion_Mobile', 'EPA-annual-emissions_1A_Combustion_Stationary', 'EPA-annual-emissions_1B1a_Abandoned_Coal', 'EPA-annual-emissions_1B1a_Coal_Mining_Surface', 'EPA-annual-emissions_1B1a_Coal_Mining_Underground', 'EPA-annual-emissions_1B2a_Petroleum', 'EPA-annual-emissions_1B2b_Natural_Gas_Distribution', 'EPA-annual-emissions_1B2b_Natural_Gas_Processing', 'EPA-annual-emissions_1B2b_Natural_Gas_Production', 'EPA-annual-emissions_1B2b_Natural_Gas_Transmission', 'EPA-annual-emissions_2B5_Petrochemical_Production', 'EPA-annual-emissions_2C2_Ferroalloy_Production', 'EPA-annual-emissions_4A_Enteric_Fermentation', 'EPA-annual-emissions_4B_Manure_Management', 'EPA-annual-emissions_4C_Rice_Cultivation', 'EPA-annual-emissions_4F_Field_Burning', 'EPA-annual-emissions_5_Forest_Fires', 'EPA-annual-emissions_6A_Landfills_Industrial', 'EPA-annual-emissions_6A_Landfills_Municipal', 'EPA-annual-emissions_6B_Wastewater_Treatment_Domestic', 'EPA-annual-emissions_6B_Wastewater_Treatment_Industrial', 'EPA-annual-emissions_6D_Composting', 'EPA-daily-emissions_5_Forest_Fires', 'EPA-monthly-emissions_1A_Combustion_Stationary', 'EPA-monthly-emissions_1B2a_Petroleum', 'EPA-monthly-emissions_1B2b_Natural_Gas_Production', 'EPA-monthly-emissions_4B_Manure_Management', 'EPA-monthly-emissions_4C_Rice_Cultivation', 'EPA-monthly-emissions_4F_Field_Burning', 'IS2SITMOGR4-cog', 'MO_NPP_npp_vgpm', 'OMI_trno2-COG', 'OMSO2PCA-COG', 'bangladesh-landcover-2001-2020', 'barc-thomasfire', 'blue-tarp-detection', 'blue-tarp-planetscope', 'caldor-fire-behavior', 'caldor-fire-burn-severity', 'campfire-albedo-wsa-diff', 'campfire-lst-day-diff', 'campfire-lst-night-diff', 'campfire-ndvi-diff', 'campfire-nlcd', 'co2-diff', 'co2-mean', 'combined_CMIP6_daily_GISS-E2-1-G_tas_kerchunk_DEMO', 'conus-reach', 'disalexi-etsuppression', 'ecco-surface-height-change', 'eis_fire_perimeter', 'facebook_population_density', 'fldas-soil-moisture-anomalies', 'frp-max-thomasfire', 'geoglam', 'grdi-cdr-raster', 'grdi-filled-missing-values-count', 'grdi-imr-raster', 'grdi-shdi-raster', 'grdi-v1-built', 'grdi-v1-raster', 'grdi-vnl-raster', 'grdi-vnl-slope-raster', 'hls-bais2-v2', 'hls-l30-002-ej-reprocessed', 'hls-s30-002-ej-reprocessed', 'hls-swir-falsecolor-composite', 'houston-aod', 'houston-aod-diff', 'houston-landcover', 'houston-lst-day', 'houston-lst-diff', 'houston-lst-night', 'houston-ndvi', 'houston-urbanization', 'landsat-nighttime-thermal', 'lis-etsuppression', 'lis-global-da-evap', 'lis-global-da-gpp', 'lis-global-da-gpp-trend', 'lis-global-da-gws', 'lis-global-da-qs', 'lis-global-da-qsb', 'lis-global-da-streamflow', 'lis-global-da-swe', 'lis-global-da-totalprecip', 'lis-global-da-tws', 'lis-global-da-tws-trend', 'lis-tvegsuppression', 'lis-tws-anomaly', 'lis-tws-nonstationarity-index', 'lis-tws-trend', 'mtbs-burn-severity', 'nceo_africa_2017', 'nightlights-hd-1band', 'nightlights-hd-monthly', 'no2-monthly', 'no2-monthly-diff', 'snow-projections-diff-245', 'snow-projections-diff-585', 'snow-projections-median-245', 'snow-projections-median-585', 'social-vulnerability-index-household', 'social-vulnerability-index-household-nopop', 'social-vulnerability-index-housing', 'social-vulnerability-index-housing-nopop', 'social-vulnerability-index-minority', 'social-vulnerability-index-minority-nopop', 'social-vulnerability-index-overall', 'social-vulnerability-index-overall-nopop', 'social-vulnerability-index-socioeconomic', 'social-vulnerability-index-socioeconomic-nopop', 'sport-lis-vsm0_100cm-percentile']

for collection_id in sorted(set(dashboard_collections)):
    collections_url = f"{STAC_API_URL}/collections/{collection_id}"
    r = requests.get(collections_url)
    if r.reason == "Not Found":
        missing_collections.append(collection_id)
        print(f"{collection_id=} {r.reason}")
    else:
        items_url = f"{STAC_API_URL}/collections/{collection_id}/items"
        r = requests.get(items_url)
        items_matched = r.json().get("context").get("matched")
        print(f"{collection_id=} {items_matched=}")
        
        if not items_matched:
            empty_collections.append(collection_id)

print(f"\n{missing_collections=}")
print(f"\n{empty_collections=}")
```

```
collection_id='CMIP245-winter-median-pr' items_matched=4
collection_id='CMIP245-winter-median-ta' items_matched=4
collection_id='CMIP585-winter-median-pr' items_matched=0
collection_id='CMIP585-winter-median-ta' items_matched=4
collection_id='EPA-annual-emissions_1A_Combustion_Mobile' items_matched=1
collection_id='EPA-annual-emissions_1A_Combustion_Stationary' items_matched=1
collection_id='EPA-annual-emissions_1B1a_Abandoned_Coal' items_matched=1
collection_id='EPA-annual-emissions_1B1a_Coal_Mining_Surface' items_matched=1
collection_id='EPA-annual-emissions_1B1a_Coal_Mining_Underground' items_matched=1
collection_id='EPA-annual-emissions_1B2a_Petroleum' items_matched=1
collection_id='EPA-annual-emissions_1B2b_Natural_Gas_Distribution' items_matched=1
collection_id='EPA-annual-emissions_1B2b_Natural_Gas_Processing' items_matched=1
collection_id='EPA-annual-emissions_1B2b_Natural_Gas_Production' items_matched=1
collection_id='EPA-annual-emissions_1B2b_Natural_Gas_Transmission' items_matched=1
collection_id='EPA-annual-emissions_2B5_Petrochemical_Production' items_matched=1
collection_id='EPA-annual-emissions_2C2_Ferroalloy_Production' items_matched=1
collection_id='EPA-annual-emissions_4A_Enteric_Fermentation' items_matched=1
collection_id='EPA-annual-emissions_4B_Manure_Management' items_matched=1
collection_id='EPA-annual-emissions_4C_Rice_Cultivation' items_matched=1
collection_id='EPA-annual-emissions_4F_Field_Burning' items_matched=1
collection_id='EPA-annual-emissions_5_Forest_Fires' items_matched=1
collection_id='EPA-annual-emissions_6A_Landfills_Industrial' items_matched=1
collection_id='EPA-annual-emissions_6A_Landfills_Municipal' items_matched=1
collection_id='EPA-annual-emissions_6B_Wastewater_Treatment_Domestic' items_matched=1
collection_id='EPA-annual-emissions_6B_Wastewater_Treatment_Industrial' items_matched=1
collection_id='EPA-annual-emissions_6D_Composting' items_matched=1
collection_id='EPA-daily-emissions_5_Forest_Fires' items_matched=366
collection_id='EPA-monthly-emissions_1A_Combustion_Stationary' items_matched=12
collection_id='EPA-monthly-emissions_1B2a_Petroleum' items_matched=12
collection_id='EPA-monthly-emissions_1B2b_Natural_Gas_Production' items_matched=12
collection_id='EPA-monthly-emissions_4B_Manure_Management' items_matched=12
collection_id='EPA-monthly-emissions_4C_Rice_Cultivation' items_matched=12
collection_id='EPA-monthly-emissions_4F_Field_Burning' items_matched=12
collection_id='IS2SITMOGR4-cog' items_matched=22
collection_id='MO_NPP_npp_vgpm' items_matched=0
collection_id='OMI_trno2-COG' items_matched=18
collection_id='OMSO2PCA-COG' items_matched=17
collection_id='bangladesh-landcover-2001-2020' items_matched=0
collection_id='barc-thomasfire' items_matched=1
collection_id='blue-tarp-detection' items_matched=372
collection_id='blue-tarp-planetscope' items_matched=372
collection_id='caldor-fire-behavior' items_matched=1
collection_id='caldor-fire-burn-severity' items_matched=1
collection_id='campfire-albedo-wsa-diff' items_matched=1
collection_id='campfire-lst-day-diff' items_matched=0
collection_id='campfire-lst-night-diff' items_matched=1
collection_id='campfire-ndvi-diff' items_matched=1
collection_id='campfire-nlcd' items_matched=1
collection_id='co2-diff' items_matched=2496
collection_id='co2-mean' items_matched=2496
collection_id='combined_CMIP6_daily_GISS-E2-1-G_tas_kerchunk_DEMO' Not Found
collection_id='conus-reach' items_matched=1
collection_id='disalexi-etsuppression' items_matched=4
collection_id='ecco-surface-height-change' items_matched=1
collection_id='eis_fire_perimeter' items_matched=0
collection_id='facebook_population_density' items_matched=1
collection_id='fldas-soil-moisture-anomalies' items_matched=0
collection_id='frp-max-thomasfire' items_matched=1
collection_id='geoglam' items_matched=46
collection_id='grdi-cdr-raster' items_matched=1
collection_id='grdi-filled-missing-values-count' items_matched=1
collection_id='grdi-imr-raster' items_matched=1
collection_id='grdi-shdi-raster' items_matched=1
collection_id='grdi-v1-built' items_matched=1
collection_id='grdi-v1-raster' items_matched=1
collection_id='grdi-vnl-raster' items_matched=1
collection_id='grdi-vnl-slope-raster' items_matched=1
collection_id='hls-bais2-v2' items_matched=1
collection_id='hls-l30-002-ej-reprocessed' Not Found
collection_id='hls-s30-002-ej-reprocessed' Not Found
collection_id='hls-swir-falsecolor-composite' items_matched=0
collection_id='houston-aod' items_matched=2
collection_id='houston-aod-diff' items_matched=1
collection_id='houston-landcover' items_matched=8
collection_id='houston-lst-day' items_matched=2
collection_id='houston-lst-diff' items_matched=0
collection_id='houston-lst-night' items_matched=2
collection_id='houston-ndvi' items_matched=2
collection_id='houston-urbanization' items_matched=0
collection_id='landsat-nighttime-thermal' items_matched=1
collection_id='lis-etsuppression' items_matched=1
collection_id='lis-global-da-evap' items_matched=7062
collection_id='lis-global-da-gpp' items_matched=7062
collection_id='lis-global-da-gpp-trend' items_matched=0
collection_id='lis-global-da-gws' items_matched=2779
collection_id='lis-global-da-qs' items_matched=7062
collection_id='lis-global-da-qsb' items_matched=7062
collection_id='lis-global-da-streamflow' items_matched=0
collection_id='lis-global-da-swe' items_matched=7062
collection_id='lis-global-da-totalprecip' items_matched=6605
collection_id='lis-global-da-tws' items_matched=7062
collection_id='lis-global-da-tws-trend' items_matched=2
collection_id='lis-tvegsuppression' items_matched=1
collection_id='lis-tws-anomaly' items_matched=6698
collection_id='lis-tws-nonstationarity-index' items_matched=1
collection_id='lis-tws-trend' items_matched=0
collection_id='mtbs-burn-severity' items_matched=1
collection_id='nceo_africa_2017' items_matched=0
collection_id='nightlights-hd-1band' items_matched=7
collection_id='nightlights-hd-monthly' items_matched=0
collection_id='no2-monthly' items_matched=0
collection_id='no2-monthly-diff' items_matched=1
collection_id='snow-projections-diff-245' items_matched=40
collection_id='snow-projections-diff-585' items_matched=0
collection_id='snow-projections-median-245' items_matched=0
collection_id='snow-projections-median-585' items_matched=0
collection_id='social-vulnerability-index-household' items_matched=0
collection_id='social-vulnerability-index-household-nopop' items_matched=0
collection_id='social-vulnerability-index-housing' items_matched=0
collection_id='social-vulnerability-index-housing-nopop' items_matched=0
collection_id='social-vulnerability-index-minority' items_matched=0
collection_id='social-vulnerability-index-minority-nopop' items_matched=0
collection_id='social-vulnerability-index-overall' items_matched=0
collection_id='social-vulnerability-index-overall-nopop' items_matched=0
collection_id='social-vulnerability-index-socioeconomic' items_matched=0
collection_id='social-vulnerability-index-socioeconomic-nopop' items_matched=0
collection_id='sport-lis-vsm0_100cm-percentile' items_matched=0

missing_collections=['combined_CMIP6_daily_GISS-E2-1-G_tas_kerchunk_DEMO', 'hls-l30-002-ej-reprocessed', 'hls-s30-002-ej-reprocessed']

empty_collections=['CMIP585-winter-median-pr', 'MO_NPP_npp_vgpm', 'bangladesh-landcover-2001-2020', 'campfire-lst-day-diff', 'eis_fire_perimeter', 'fldas-soil-moisture-anomalies', 'hls-swir-falsecolor-composite', 'houston-lst-diff', 'houston-urbanization', 'lis-global-da-gpp-trend', 'lis-global-da-streamflow', 'lis-tws-trend', 'nceo_africa_2017', 'nightlights-hd-monthly', 'no2-monthly', 'snow-projections-diff-585', 'snow-projections-median-245', 'snow-projections-median-585', 'social-vulnerability-index-household', 'social-vulnerability-index-household-nopop', 'social-vulnerability-index-housing', 'social-vulnerability-index-housing-nopop', 'social-vulnerability-index-minority', 'social-vulnerability-index-minority-nopop', 'social-vulnerability-index-overall', 'social-vulnerability-index-overall-nopop', 'social-vulnerability-index-socioeconomic', 'social-vulnerability-index-socioeconomic-nopop', 'sport-lis-vsm0_100cm-percentile']
```

**Comment by botanical** [comment]
https://github.com/NASA-IMPACT/veda-data/pull/132 PR to restructure `ingestions` based on our conversation on slack

**Comment by j08lue** [comment]
Would it be easy enough to rename this collection here before / as we publish the production catalog?

- https://github.com/NASA-IMPACT/veda-data/issues/141
