### ISSUE TITLE
Complete NLCD Collections Promotion to Production

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-data#170]
## What
This issue is to collect the remaining data tasks required to publish the NLCD dataset to the earthdata dashboard.

**Blocked PR** [veda-config/NLCD Dataset Landing Page #432](https://github.com/NASA-IMPACT/veda-config/pull/432)

## Tasks
- [x] [Add custom colormap to veda-backend](https://github.com/NASA-IMPACT/veda-backend/issues/429) for the categorical NLCD dataset. This colormap requires a URL so long that it is blocked by the MCP firewall so we have to store it in the tiler.
- [x] Promote backend with custom nlcd colormap to production raster api at openveda.cloud/api/raster
- [x] Update the renders configuration for the two NLCD collections to use the custom colormap created above in [veda-data PR #166](https://github.com/NASA-IMPACT/veda-data/pull/166) and in the production catalog

## Unblocked veda-config PR
Now [veda-config/NLCD Dataset Landing Page #432](https://github.com/NASA-IMPACT/veda-config/pull/432) can be updated to use the new renders configuration and publish to the dashboard

**Comment by anayeaye** [comment]
Note on progress:

The nlcd colormap is now included in the backend titiler and is deployed to dev (you can see it in action here: https://github.com/NASA-IMPACT/veda-backend/issues/429#issuecomment-2392181022). I have updated the renders configuration in the nlcd-annual-conus collections in dev, staging, and prod but the updated titiler is only in dev at the moment (we have some breaking changes that need to be rolled out in staging and prod).

**nlcd-annual-conus status by stage**
- dev: titiler upgraded and collection uses new nlcd colormap WORKS
- staging: titiler not yet upgraded but collection now uses new nlcd colormap NOT YET WORKING
- dev: titiler not yet upgraded but collection now uses new nlcd colormap NOT YET WORKING

**Comment by anayeaye** [comment]
The custom colormap is now deployed to production and working as expected 

https://openveda.cloud/api/raster/collections/nlcd-annual-conus/items/nlcd_2001_cog_v2/preview.png?bidx=1&assets=landcover&nodata=0&resampling=nearest&colormap_name=nlcd
