### ISSUE TITLE
Create COGs and STAC for Multiple Datasets related to cyclones

### ISSUE THREAD

**Issue by siddharth0248** [NASA-IMPACT/veda-data#214]
#### Description  
We aim to create Cloud Optimized GeoTIFFs (COGs) and generate corresponding STAC metadata for the following datasets:  

- [ ] GOES16 (Bands 2, 8, 13)  
- [ ] IMERG  
- [ ] MODIS IR  
- [ ] VIIRS IR  
- [ ] CYGNSS  

#### Requirements  
1. **Event-Based Clipping**:  
   - COGs should be clipped to the specified area of interest relevant to the event.  

2. **STAC Metadata**:  
   - Generate STAC metadata for each dataset.  
   e.g.  goes-16-hurricane-name

3. **Use of `stactools`**:  
   - Leverage `stactools` for datasets/products it supports.  
   - If `stactools` does not support a product, contribute a `cogify` function for that product.  

#### Resources  
- **Code for COG Transformation**: []  
- **Sample Datasets**: []  
- **COGs for Area of Interest**: []  

#### Tasks  
- [ ] Implement `cogify` function for each dataset.  
- [ ] Clip COGs to the area of interest for the specific event.  
- [ ] Generate STAC metadata for the processed COGs.  
- [ ] Contribute missing `cogify` implementations to `stactools`.  
- [ ] Validate generated COGs and STAC metadata.  

#### Notes  
- Ensure compatibility with existing `stactools` modules where applicable.  
- Validate that the clipped COGs align accurately with the defined area of interest.

**Comment by siddharth0248** [comment]
<img width="1204" alt="Image" src="https://github.com/user-attachments/assets/0afdd2cc-a611-4572-92f7-31bd893c16b0" />

**Comment by siddharth0248** [comment]
@j08lue @gadomski 
I will add details in this ticket

**Comment by abarciauskas-bgse** [comment]
@siddharth0248 do you think we could use titiler-cmr for some of these datasets? Specifically if they are gridded datasets. I'm not sure which specific products are intended to be used, so if I had that information I could say for sure if we could visualize them with titiler-cmr. We wouldn't be able to clip them but if we could configure the maps themselves (assuming maps embedded in a story) are zoomed into the appropriate bbox, titiler-cmr could still work well.

**Comment by siddharth0248** [comment]
We can leverage it for a few datasets like IMERG. @amarouane-ABDELHAK  what is your say?

**Comment by abarciauskas-bgse** [comment]
I would be happy to discuss this more, but just as an FYI, one IMERG dataset is available via titiler-cmr (https://www.earthdata.nasa.gov/dashboard/data-catalog/GPM_3IMERGDF.v07)
